DROP TABLE IF EXISTS TICKET_AUDIT_LOG, WALLET_TRANSACTIONS, tickets, ticket_type, 
  PROMOTIONS, PAYMENTS, BOOKINGS, WALLETS, ADD_MONEY_REQUESTS, WISHLIST, 
  EVENTS, ORGANIZERS, USERS CASCADE;


CREATE TABLE USERS
(
USER_ID CHAR(15) PRIMARY KEY,
USER_NAME VARCHAR(40) NOT NULL, 
EMAIL VARCHAR (100) UNIQUE NOT NULL,
PASSWORD VARCHAR(60) NOT NULL,
GENDER VARCHAR (20) CHECK (GENDER IN ('male','female','other','prefer_not_to_say')),
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ACCOUNT_STATUS VARCHAR(20) DEFAULT 'active' CHECK (ACCOUNT_STATUS IN ('active', 'deactivated'))-- active/deactivated
);


CREATE TABLE ORGANIZERS
(
  ORGANIZER_ID CHAR(15) PRIMARY KEY REFERENCES USERS(USER_ID) ON DELETE RESTRICT, 
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  COMPANY_NAME VARCHAR(50) NOT NULL, 
  BIO TEXT
);

CREATE TABLE EVENTS 
(
  EVENT_ID CHAR(15) PRIMARY KEY, 
  ORGANIZER_ID CHAR(15) NOT NULL REFERENCES ORGANIZERS(ORGANIZER_ID), 
  TITLE VARCHAR (100) NOT NULL UNIQUE, 
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  EVENT_DATE_TIME TIMESTAMP NOT NULL, 
  VENUE VARCHAR(50),
  DESCRIBE_EVENT TEXT,
  STATUS VARCHAR(20) DEFAULT 'scheduled' CHECK (STATUS IN ('scheduled', 'cancelled', 'completed')),-- scheduled/cancelled/completed
  CONSTRAINT uq_event_per_organizer_date UNIQUE (ORGANIZER_ID, TITLE, EVENT_DATE_TIME)
);

CREATE TABLE WISHLIST 
(
  USER_ID CHAR(15) NOT NULL REFERENCES USERS(USER_ID) ON DELETE CASCADE,
  EVENT_ID CHAR(15) NOT NULL REFERENCES EVENTS(EVENT_ID) ON DELETE CASCADE,
  ADDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_wl 
  PRIMARY KEY (USER_ID, EVENT_ID)
);

CREATE TABLE ADD_MONEY_REQUESTS
(
  REQUEST_ID CHAR(15) PRIMARY KEY,
  USER_ID CHAR(15) NOT NULL REFERENCES USERS(USER_ID) ON DELETE RESTRICT,
  AMOUNT NUMERIC(10,2) NOT NULL CHECK (AMOUNT > 0),
  STATUS VARCHAR(20) DEFAULT 'pending' CHECK (STATUS IN ('pending', 'approved', 'rejected')),
  REQUESTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
  PROCESSED_AT TIMESTAMP 
);

CREATE TABLE WALLETS 
(
  WALLET_ID CHAR(15) PRIMARY KEY ,
  USER_ID CHAR(15) NOT NULL UNIQUE REFERENCES USERS(USER_ID) ON DELETE RESTRICT,
  BALANCE NUMERIC(10,2) DEFAULT 10000 CHECK (BALANCE>=0),
  LAST_USED TIMESTAMP 
);

CREATE TABLE BOOKINGS 
(
  BOOKING_ID CHAR(15) PRIMARY KEY, 
  EVENT_ID CHAR(15) NOT NULL REFERENCES EVENTS(EVENT_ID) ON DELETE RESTRICT,
  USER_ID CHAR(15) NOT NULL REFERENCES USERS(USER_ID) ON DELETE RESTRICT,
  BOOKING_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  BK_STATUS VARCHAR(20) DEFAULT 'pending' CHECK (BK_STATUS IN ('pending', 'confirmed', 'cancelled')),
  TOTAL_COST NUMERIC(10,2) DEFAULT 0
);

CREATE TABLE PAYMENTS (
  PAYMENT_ID CHAR(15) PRIMARY KEY,
  BOOKING_ID CHAR(15) NOT NULL REFERENCES BOOKINGS(BOOKING_ID) ON DELETE CASCADE,
  AMOUNT NUMERIC(10,2) NOT NULL CHECK (AMOUNT > 0),
  DEBITED_FROM CHAR(15) NOT NULL REFERENCES WALLETS(WALLET_ID) ON DELETE RESTRICT,
  PAYMENT_METHOD VARCHAR(15) CHECK (PAYMENT_METHOD IN ('wallet', 'card', 'upi', 'netbanking')),
  TRANSACTION_REF VARCHAR(20),
  PAID_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PROMOTIONS 
(
  PROMO_ID CHAR(15) PRIMARY KEY,
  BOOKING_ID CHAR(15) REFERENCES BOOKINGS(BOOKING_ID),
  CODE VARCHAR(10) NOT NULL, 
  VALID_FROM TIMESTAMP NOT NULL, 
  VALID_TO TIMESTAMP NOT NULL,
  DISCOUNT_TYPE VARCHAR(20) NOT NULL CHECK (DISCOUNT_TYPE IN ('percentage', 'flat')),
  DISCOUNT_VALUE NUMERIC(10,2) NOT NULL CHECK (DISCOUNT_VALUE > 0),
  CONSTRAINT chk_promo_dates CHECK (VALID_TO > VALID_FROM),
  CONSTRAINT chk_promo_pct CHECK (DISCOUNT_TYPE <> 'percentage' OR DISCOUNT_VALUE <= 100)
);

CREATE TABLE ticket_type(
  TYPE_ID CHAR(15) PRIMARY KEY,
  EVENT_ID CHAR(15) REFERENCES EVENTS(EVENT_ID) ON DELETE RESTRICT,
  CATEGORY VARCHAR(10) CHECK (CATEGORY IN ('REGULAR', 'VIP', 'PLATINUM', 'EARLY_BIRD')),
  QUANTITY_AVAILABLE INTEGER NOT NULL DEFAULT 0 CHECK (QUANTITY_AVAILABLE >= 0),
  STATUS VARCHAR(20) DEFAULT 'active' CHECK (STATUS IN ('active', 'inactive')), -- active/inactive
  PRICE NUMERIC(10,2) NOT NULL CHECK (PRICE > 0)
);

CREATE TABLE tickets (
  TICKET_ID      CHAR(15) PRIMARY KEY,
  BOOKING_ID      CHAR(15) NOT NULL,
  TICKET_TYPE_ID  CHAR(15) NOT NULL,
  SEAT_NUMBER     VARCHAR(10)NOT NULL,
  PRICE_PAID NUMERIC(10,2) NOT NULL CHECK (PRICE_PAID > 0),
  CONSTRAINT fk_tickets_booking
    FOREIGN KEY (booking_id) REFERENCES bookings(booking_id)
    ON DELETE CASCADE,
  CONSTRAINT fk_tickets_type 
  FOREIGN KEY (ticket_type_id) REFERENCES TICKET_TYPE(TYPE_ID) ON DELETE RESTRICT,
  CONSTRAINT uq_ticket_seat
    UNIQUE (ticket_type_id, seat_number)
);

CREATE TABLE WALLET_TRANSACTIONS
(
  TRANSACTION_ID CHAR(15) PRIMARY KEY,
  WALLET_ID CHAR(15) NOT NULL REFERENCES WALLETS(WALLET_ID), 
  TYPE VARCHAR(20) NOT NULL CHECK (TYPE IN ('deposit', 'payment', 'refund')),       -- deposit/payment/refund
  AMOUNT NUMERIC(10,2) NOT NULL CHECK (AMOUNT > 0),
  REASON VARCHAR(100),
  REFERENCE_ID CHAR(15),         -- e.g. related booking_id or request_id
  BALANCE_AFTER NUMERIC(10,2),
  HAPPENED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TICKET_AUDIT_LOG
(
  LOG_ID CHAR(15) PRIMARY KEY,
  TYPE_ID CHAR(15) NOT NULL REFERENCES ticket_type(TYPE_ID),
  OLD_QUANTITY INTEGER,
  NEW_QUANTITY INTEGER,
  OLD_STATUS VARCHAR(20),
  NEW_STATUS VARCHAR(20),
  CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);