-- DROP TABLE IF EXISTS TICKET_AUDIT_LOG, WALLET_TRANSACTIONS, tickets, ticket_type, 
--   PROMOTIONS, PAYMENTS, BOOKINGS, WALLETS, ADD_MONEY_REQUESTS, WISHLIST, 
--   EVENTS, ORGANIZERS, USERS CASCADE;
CREATE TABLE USERS
(
USER_ID CHAR(15) PRIMARY KEY,
USER_NAME VARCHAR(40) NOT NULL, 
EMAIL VARCHAR (100) UNIQUE NOT NULL,
PASSWORD VARCHAR(60) NOT NULL,
GENDER VARCHAR (20), -- PREFER NOT TO SAY
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE ORGANIZERS
(
  ORGANIZER_ID CHAR(15) PRIMARY KEY REFERENCES USERS(USER_ID),  
  CREATED_AT TIMESTAMP,
  COMPANY_NAME VARCHAR(50) NOT NULL, 
  BIO TEXT
);

CREATE TABLE EVENTS 
(
  EVENT_ID CHAR(15) PRIMARY KEY, 
  ORGANIZER_ID CHAR(15) NOT NULL REFERENCES ORGANIZERS(ORGANIZER_ID), 
  TITLE VARCHAR (100) NOT NULL UNIQUE, 
  EVENT_DATE_TIME TIMESTAMP NOT NULL, 
  VENUE VARCHAR(50),
  DESCRIBE_EVENT TEXT,
  STATUS VARCHAR(20) DEFAULT 'scheduled'-- scheduled/cancelled/completed
);

CREATE TABLE WISHLIST 
(
  USER_ID CHAR(15) NOT NULL REFERENCES USERS(USER_ID),
  EVENT_ID CHAR(15) NOT NULL REFERENCES EVENTS(EVENT_ID),
  ADDED_AT TIMESTAMP,
  CONSTRAINT pk_wl 
  PRIMARY KEY (USER_ID,EVENT_ID)
  );

CREATE TABLE ADD_MONEY_REQUESTS
(
  REQUEST_ID CHAR(15) PRIMARY KEY,
  USER_ID CHAR(15)  REFERENCES USERS(USER_ID),
  AMOUNT NUMERIC(10,2) NOT NULL, 
  STATUS VARCHAR(20),-- PENDING/ APPROVED 
  REQUESTED_AT TIMESTAMP, 
  PROCESSED_AT TIMESTAMP 
);

CREATE TABLE WALLETS 
(
  WALLET_ID CHAR(15) PRIMARY KEY ,
  USER_ID CHAR(15) NOT NULL UNIQUE REFERENCES USERS(USER_ID),
  BALANCE NUMERIC(10,2) DEFAULT 10000,
  LAST_USED TIMESTAMP 
);

CREATE TABLE BOOKINGS 
(
  BOOKING_ID CHAR(15) PRIMARY KEY, 
  EVENT_ID CHAR(15)  NOT NULL REFERENCES EVENTS(EVENT_ID),
  USER_ID CHAR(15) NOT NULL REFERENCES USERS(USER_ID), 
  BOOKING_TIME TIMESTAMP, 
  BK_STATUS VARCHAR (20),
  TOTAL_COST NUMERIC(10,2)
);

CREATE TABLE PAYMENTS (
  PAYMENT_ID CHAR(15) PRIMARY KEY, 
  BOOKING_ID CHAR(15) REFERENCES BOOKINGS(BOOKING_ID),
  AMOUNT NUMERIC(10,2) ,
  DEBITED_FROM CHAR(15) REFERENCES WALLETS(WALLET_ID),
  PAYMENT_METHOD VARCHAR(15),
  TRANSACTION_REF VARCHAR(20),
  PAID_AT TIMESTAMP
);
 
CREATE TABLE PROMOTIONS 
(
  PROMO_ID CHAR(15) PRIMARY KEY,
  BOOKING_ID CHAR(15) REFERENCES BOOKINGS(BOOKING_ID),
  CODE CHAR(10) NOT NULL UNIQUE, 
  VALID_FROM TIMESTAMP, 
  VALID_TO TIMESTAMP,
  DISCOUNT_TYPE CHAR(20),
  DISCOUNT_VALUE NUMERIC(10,2)
);

CREATE TABLE ticket_type(
  TYPE_ID CHAR(15) PRIMARY KEY,
  EVENT_ID CHAR(15) REFERENCES EVENTS(EVENT_ID),
  CATEGORY VARCHAR(10),--REGULAR/VIP ETC.
  QUANTITY_AVAILABLE INTEGER,
  PRICE NUMERIC(10,2)
);


CREATE TABLE tickets (
  TICKET_ID      CHAR(15) PRIMARY KEY,
  BOOKING_ID      CHAR(15) NOT NULL,
  TICKET_TYPE_ID  CHAR(15) NOT NULL,
  SEAT_NUMBER     VARCHAR(10)NOT NULL,
  PRICE_PAID     NUMERIC(10,2) NOT NULL,
  CONSTRAINT fk_tickets_booking
    FOREIGN KEY (booking_id) REFERENCES bookings(booking_id)
    ON DELETE CASCADE,
  CONSTRAINT fk_tickets_type 
  FOREIGN KEY (ticket_type_id) REFERENCES TICKET_TYPE(TYPE_ID),
  CONSTRAINT uq_ticket_seat
    UNIQUE (ticket_type_id, seat_number)
);

CREATE TABLE WALLET_TRANSACTIONS
(
  TRANSACTION_ID CHAR(15) PRIMARY KEY,
  WALLET_ID CHAR(15) NOT NULL REFERENCES WALLETS(WALLET_ID), 
  TYPE VARCHAR(20) NOT NULL,        -- deposit/payment/refund
  AMOUNT NUMERIC(10,2) NOT NULL,
  REASON VARCHAR(100),
  REFERENCE_ID CHAR(15),         -- e.g. related booking_id or request_id
  BALANCE_AFTER NUMERIC(10,2),
  HAPPENED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE TICKET_AUDIT_LOG
(
  LOG_ID CHAR(15) PRIMARY KEY,
  TYPE_ID CHAR(15) NOT NULL REFERENCES ticket_type(TYPE_ID),
  OLD_QUANTITY INTEGER,
  NEW_QUANTITY INTEGER,
  CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);